### PR TITLE
add features to nav bar and table

### PR DESCRIPTION
**Pull request by yasaswiraj**
1) tabs added to navbar
2)now added request can be fetched from database

### CODE REVIEW

**Comment by yasaswiraj** [comment]
table has authorization
new remarks UI updated

**Comment by Saravanan-Jodavula** [comment]
@yasaswiraj the app is not redirecting to faculty dashboard after faculty login. Also, faculty dashboard table not rendering values. Please look into it.
image

**Comment by Saravanan-Jodavula** [comment]
@yasaswiraj the problem with faculty table still persists and faculty login redirect is not happening. Table's giving 404 onmount. 
**note :** The endpoints for dashboards have been changed. faculty dashboard's enpoint is `/facultydashboard`
Please look into the matter.

**Comment by yasaswiraj** [comment]
HELLO @Saravanan-Jodavula

**Pull request merged**
